<?
/***************************************************************************
 *                               ads_rss2.php
 *                            -------------------
 *   begin                : Wednesday, Feb 15, 2006
 *   copyright            : (C) 2006 Peter Mansion
 *   email                : support@phpca.net
 *
 *   $Id: ads_rss2.php,v0.5.0 2005/10/30 20:10:00 pmansion Exp $
 *
 *
 ***************************************************************************/

/*************************************************************************** 
* 
* This program is free software; you can redistribute it and/or modify 
* it under the terms of the GNU General Public License as published by 
* the Free Software Foundation; either version 2 of the License, or 
* (at your option) any later version. 
* 
***************************************************************************/ 

define('IN_PHPBB', true);
$phpbb_root_path = './';
include($phpbb_root_path . 'extension.inc');
include($phpbb_root_path . 'common.'.$phpEx);

$ads_root_path = $phpbb_root_path . 'ads_mod/';
include($ads_root_path . 'ads_common.'.$phpEx);

header("Content-Type: text/xml"); 

$server_protocol = ( $board_config['cookie_secure'] ) ? 'https://' : 'http://';

$sql = 'SELECT * 
		FROM '. ADS_ADVERTS_TABLE .' 
		ORDER BY id DESC 
		LIMIT 0,5';

$result = $db->sql_query($sql);

$date = date("m/d/Y; G:i:s A T"); 

$rss_title = "".$board_config['sitename']." Syndication"; 
$website_url = $server_protocol.$board_config['server_name']."".$board_config['script_path']."".append_sid("index.".$phpEx).""; 
$home_url = $server_protocol.$board_config['server_name']."".$board_config['script_path'].""; 

print ("<!-- RSS generated by ". htmlentities($rss_title) ." on ". htmlentities($date) ." -->\n"); 
print ("<rss version=\"2.0\">\n\n"); 
print ("<channel>\n"); 
print ("<title>". htmlentities($rss_title) ."</title>\n"); 
print ("<link>". htmlentities($home_url) ."</link>\n"); 
print ("<description>". htmlentities($rss_title) ."</description>\n"); 
print ("<language>en-gb</language>\n\n"); 

while ($row = $db->sql_fetchrow($result)) 
{ 
	print ("<item>\n"); 
	print ("<title>" . htmlentities($row['title']) . "</title>\n"); 
	print ("<link>". htmlentities($home_url) ."ads_item.".$phpEx."?id=" . htmlentities($row['id']) . "</link>\n"); 
	print ("<description>". htmlentities($row['short_desc']) . "</description>\n"); 
	print ("</item>\n\n"); 
} 

print ("</channel>\n"); 
print ("</rss>"); 

$db->sql_close(); 
?>